# === SITE INFORMATION ===
site_name: My Machine Learning Notes
site_url: https://LewisDean22.github.io/Lewis-ML-Notes/
site_author: Lewis Dean
site_description: The machine learning knowledge base of Lewis Dean

# === REPOSITORY ===
repo_url: https://github.com/LewisDean22/Lewis-ML-Notes
repo_name: Lewis' ML Repo

# === THEME ===
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    # Navigation
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.indexes
    - navigation.path
    - navigation.tracking
    # Table of contents
    - toc.follow
    # Search
    - search.suggest
    - search.highlight
    # Content
    - content.code.copy

# === MARKDOWN EXTENSIONS ===
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - footnotes

# === MATH SUPPORT ===
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/justify.css

# === PLUGINS ===
plugins:
  - search
  - minify:
      minify_html: true

# === NAVIGATION ===
nav:
  - Home: index.md
  - Concepts:
      # - fundamentals/index.md
      - ML Paradigms: concepts/ml_paradigms.md
      - Fundamental Algorithms:
          - KNN: concepts/fundamental_algorithms/knn.md
          - Decision Trees: concepts/fundamental_algorithms/decision_trees.md
      - Clustering:
          - K Means Clustering: concepts/clustering/k_means.md
          - Hierarchical Clustering: concepts/clustering/hierarchical_clustering.md
      - Deep Learning:
          - Neural Networks 101: concepts/deep_learning/neural_networks_101.md
          - CNNs: concepts/deep_learning/cnn.md
  # - Projects:
  #     - projects/index.md

# === FOOTER ===
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LewisDean22
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lewis-michael-dean/

